### ISSUE TITLE
当我按照教程集成使用时，出现了一下问题

### ISSUE THREAD

**Issue by BlackJia** [feflow/git-commit-style-guide#1]
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! java-thead-learn@0.1.0 commitmsg: `validate-commit-msg`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the java-thead-learn@0.1.0 commitmsg script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

**Comment by cpselvis** [comment]
你在项目的package.json中加入开发依赖后：
```
    "devDependencies": {
      "commitizen": "^2.3.0",
      "validate-commit-msg": "^2.11.1",
      "conventional-changelog-cli": "^1.2.0",
      "husky": "^0.13.1"
    }
```
有执行 **npm install** 吗？从这个报错日志上看是没有安装相关依赖
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
